#!/usr/bin/env node
// scaffold-readme.js — v78 emit project-root README.md derived from
// PROJECT_KNOWLEDGE.md (project name + summary if present) + standard
// dev/test/build/docker sections.
//
// Idempotent. Marker: '<!-- Generated by scaffold-readme -->'.
'use strict';

var fs = require('fs');
var path = require('path');

function parseArgs(argv) {
  var out = {};
  for (var i = 2; i < argv.length; i++) {
    var a = argv[i];
    if (a === '--target') out.target = argv[++i];
    else if (a === '--knowledge') out.knowledge = argv[++i];
    else if (a === '--name') out.name = argv[++i];
    else if (a === '--force') out.force = true;
    else if (a === '--dry-run') out.dryRun = true;
  }
  if (!out.target) { console.error('Usage: scaffold-readme --target PROJECT_ROOT [--knowledge PROJECT_KNOWLEDGE.md] [--name "Project Name"]'); process.exit(1); }
  return out;
}

function marker() { return '<!-- Generated by scaffold-readme — DO NOT EDIT BY HAND. Re-run to refresh. -->'; }

function writeIfManaged(file, content, force, dryRun) {
  if (fs.existsSync(file)) {
    var existing = fs.readFileSync(file, 'utf-8');
    if (!/Generated by scaffold-readme/.test(existing) && !force) {
      return { written: false, reason: 'exists-handauthored' };
    }
    if (existing === content) return { written: false, reason: 'unchanged' };
  }
  if (dryRun) return { written: false, reason: 'dry-run' };
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
  return { written: true };
}

function extractFromKnowledge(knowledgePath, fallbackName) {
  var out = { name: fallbackName || 'App', summary: '' };
  if (!knowledgePath || !fs.existsSync(knowledgePath)) return out;
  var content = fs.readFileSync(knowledgePath, 'utf-8');
  // Title line: first `# X` heading
  var titleMatch = /^#\s+(.+)$/m.exec(content);
  if (titleMatch) out.name = titleMatch[1].trim();
  // Summary: first paragraph after the title
  var afterTitle = content.split(/^#\s+.+$/m)[1] || '';
  var firstPara = afterTitle.split(/\n\s*\n/).map(function (s) { return s.trim(); }).filter(Boolean)[0] || '';
  // Skip if first para is itself a heading
  if (firstPara && !/^#/.test(firstPara)) {
    out.summary = firstPara.replace(/\n/g, ' ').slice(0, 400);
  }
  return out;
}

function buildReadme(info) {
  return [
    marker(),
    '# ' + info.name,
    '',
    info.summary || '_(summary auto-derived from `.claude-project/docs/PROJECT_KNOWLEDGE.md` when present)_',
    '',
    '## Stack',
    '',
    '- **Backend** — NestJS, TypeORM, PostgreSQL, JWT (httpOnly cookies)',
    '- **Frontend** — React Router 7 (framework mode), Vite, Tailwind v4, Redux + async thunks, Shadcn/UI',
    '- **Tests** — Jest (backend), Vitest + RTL + MSW (frontend), Playwright (e2e)',
    '',
    '## Quickstart',
    '',
    '```bash',
    '# 1. Start postgres + both services together',
    'docker compose up',
    '',
    '# 2. Or run locally:',
    'cd backend && npm install && npm run start:dev',
    'cd frontend && npm install && npm run dev',
    '```',
    '',
    'Backend on `http://localhost:3000`, frontend on `http://localhost:5173`.',
    '',
    '## Common scripts',
    '',
    '```bash',
    '# Backend',
    'cd backend',
    'npm run start:dev      # watch + reload',
    'npm test               # unit + e2e',
    'npx tsc --noEmit       # typecheck',
    'npm run build',
    'npm run seed           # populate dev DB with _fixtures.yaml users',
    '',
    '# Frontend',
    'cd frontend',
    'npm run dev',
    'npm test               # vitest',
    'npx tsc --noEmit',
    'npm run build',
    '```',
    '',
    '## Environment',
    '',
    'See `backend/.env.example` and `frontend/.env.example` for required env vars.',
    'Copy each `.env.example` → `.env` and fill in.',
    '',
    '## Project layout',
    '',
    '```',
    'backend/   NestJS app (src/modules/, src/core/, src/infrastructure/)',
    'frontend/  React Router 7 app (app/ — NOT src/, import alias ~/)',
    '.claude-project/',
    '  docs/             PROJECT_KNOWLEDGE.md / PROJECT_API.md / PROJECT_DATABASE.md',
    '  user_stories/     YAML acceptance criteria for Playwright suites',
    '  design/           DESIGN_SYSTEM.md + HTML prototypes',
    '```',
    '',
  ].join('\n');
}

function main() {
  var args = parseArgs(process.argv);
  var knowledge = args.knowledge || path.join(args.target, '.claude-project/docs/PROJECT_KNOWLEDGE.md');
  var info = extractFromKnowledge(knowledge, args.name);
  var dst = path.join(args.target, 'README.md');
  var r = writeIfManaged(dst, buildReadme(info), args.force, args.dryRun);
  console.log('scaffold-readme: README.md=' + (r.written ? 'wrote' : r.reason) + ' (name: "' + info.name + '")');
}

main();
