#!/usr/bin/env bash
# write-outcome.sh — back-fill the "## Outcome" section of HYPOTHESIS.md
# from cell artifacts (PIPELINE_STATUS.md, BACKEND_IMPLEMENTATION_REPORT.md,
# STORY_QA_REPORT.md). Idempotent — only overwrites if the placeholder
# "_To be filled in_" string is still present.
#
# Usage:
#   bash write-outcome.sh <run_root>
#   bash write-outcome.sh experiments/parallel-runs/runs/20260505T204525Z-overnight-ship-v23-tuned
#
# Also invoked from aggregate.sh on every run.

set -u

RUN_ROOT="${1:-}"
if [ -z "$RUN_ROOT" ] || [ ! -d "$RUN_ROOT" ]; then
  echo "Usage: $0 <run_root>" >&2
  exit 1
fi

HYP="$RUN_ROOT/HYPOTHESIS.md"
if [ ! -f "$HYP" ]; then
  echo "[outcome] no HYPOTHESIS.md in $RUN_ROOT — skip" >&2
  exit 0
fi
if ! grep -q "_To be filled in" "$HYP" 2>/dev/null; then
  echo "[outcome] HYPOTHESIS.md already has manual outcome — skip ($HYP)" >&2
  exit 0
fi

TMP=$(mktemp /tmp/hyp-outcome.XXXXXX)
{
  echo "## Outcome"
  echo ""
  echo "_Auto-generated by write-outcome.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)._"
  echo ""
  echo "### Per-cell phase ladder"
  echo ""
  echo "| Cell | spec | prd | database | user-stories | design | backend | frontend | integrate | test-api | test-browser | ship |"
  echo "|---|---|---|---|---|---|---|---|---|---|---|---|"
  for cell_dir in "$RUN_ROOT"/run-*; do
    [ -d "$cell_dir" ] || continue
    cell=$(basename "$cell_dir" | sed 's/^run-//')
    ps=$(find "$cell_dir/.claude-project" -name PIPELINE_STATUS.md 2>/dev/null | head -1)
    row="| $cell"
    if [ -z "$ps" ]; then
      for _ in spec prd database user-stories design backend frontend integrate test-api test-browser ship; do
        row="$row | -"
      done
    else
      for phase in spec prd database user-stories design backend frontend integrate test-api test-browser ship; do
        status=$(awk -v p="$phase" -F'|' '$2 ~ "^ *"p" *$" {gsub(/^ +| +$/,"",$3); print $3; exit}' "$ps")
        [ -z "$status" ] && status="-"
        case "$status" in
          Complete) status="✅" ;;
          Failed)   status="❌" ;;
          Pending)  status="⋯" ;;
        esac
        row="$row | $status"
      done
    fi
    row="$row |"
    echo "$row"
  done
  echo ""
  echo "### Per-cell metrics"
  echo ""
  echo "| Cell | backend tests_passing | stories total/pass/fail | bugs P0/P1/P2 | story pass_rate |"
  echo "|---|---|---|---|---|"
  for cell_dir in "$RUN_ROOT"/run-*; do
    [ -d "$cell_dir" ] || continue
    cell=$(basename "$cell_dir" | sed 's/^run-//')
    bir=$(find "$cell_dir/.claude-project" -name BACKEND_IMPLEMENTATION_REPORT.md 2>/dev/null | head -1)
    # Per-frontend reports: STORY_QA_REPORT_<frontend>.md (PR #63 race fix).
    # Sum metrics across all per-frontend files. Plain STORY_QA_REPORT.md
    # (no suffix) is preserved for single-frontend runs / older artifacts.
    sqr_files=$(find "$cell_dir/.claude-project" \( -name 'STORY_QA_REPORT.md' -o -name 'STORY_QA_REPORT_*.md' \) 2>/dev/null)
    tests="-"; stories="-"; bugs="-"; rate="-"
    [ -f "$bir" ] && tests=$(awk '/^tests_passing:/{print $2; exit}' "$bir")
    if [ -n "$sqr_files" ]; then
      tot_total=0; tot_pass=0; tot_fail=0; tot_p0=0; tot_p1=0; tot_p2=0
      while IFS= read -r sqr; do
        [ -f "$sqr" ] || continue
        v=$(awk '/^stories_total:/{print $2; exit}' "$sqr"); tot_total=$((tot_total + ${v:-0}))
        v=$(awk '/^stories_passed:/{print $2; exit}' "$sqr"); tot_pass=$((tot_pass + ${v:-0}))
        v=$(awk '/^stories_failed:/{print $2; exit}' "$sqr"); tot_fail=$((tot_fail + ${v:-0}))
        v=$(awk '/^bugs_p0:/{print $2; exit}' "$sqr"); tot_p0=$((tot_p0 + ${v:-0}))
        v=$(awk '/^bugs_p1:/{print $2; exit}' "$sqr"); tot_p1=$((tot_p1 + ${v:-0}))
        v=$(awk '/^bugs_p2:/{print $2; exit}' "$sqr"); tot_p2=$((tot_p2 + ${v:-0}))
      done <<< "$sqr_files"
      if [ "$tot_total" -gt 0 ]; then
        stories="${tot_total}/${tot_pass}/${tot_fail}"
        bugs="${tot_p0}/${tot_p1}/${tot_p2}"
        rate=$(awk -v p="$tot_pass" -v t="$tot_total" 'BEGIN{ if(t>0) printf "%.2f", p/t; else print "0.00"}')
      fi
    fi
    echo "| $cell | $tests | $stories | $bugs | $rate |"
  done
  echo ""
  echo "_Legend: ✅=Complete, ❌=Failed, ⋯=Pending, -=missing artifact. Add a manual narrative paragraph below if helpful._"
} > "$TMP"

awk -v block_file="$TMP" '
  /^## Outcome$/ { in_outcome=1; while ((getline line < block_file) > 0) print line; close(block_file); next }
  in_outcome && /^## / { in_outcome=0 }
  !in_outcome { print }
' "$HYP" > "$HYP.tmp" && mv "$HYP.tmp" "$HYP"
rm -f "$TMP"
echo "[outcome] wrote $HYP"
